M48
; DRILL file KiCad 10.0.6 date 2026-10-07T00:54:29
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-07T00:54:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X83.34Y-98.5
X93.5Y-98.5
X106.34Y-98.5
X116.5Y-98.5
X128.34Y-98.5
X138.5Y-98.5
T2
X88.42Y-98.5
X111.42Y-98.5
X133.42Y-98.5
M30
